fix: cleanup player-ui before destroying player on unmount
bitmovin/bitmovin-player-react pull request #18
Opened 2024-11-13 20:36 UTC by ReallyBadNews

Hi all, I raised this as a [Bitmovin Support Ticket](https://bitmovin.zendesk.com/hc/en-us/requests/22796) last month. I was told it would be raised internally but I had some time to attempt a fix. Let me know if you spot anything that's amiss

## Please describe the unexpected behavior you are experiencing:

There is an error is thrown from the Bitmovin player script when unmounting the component

```
{
  "code": 1001,
  "name": "API_NOT_AVAILABLE",
  "message": "Cannot use the `player.isCasting` API: the player has already been destroyed."
}
```

## Please outline how you expect it should work:

The player's cleanup should not destroy the player prior to other resources being cleaned up

## Please provide the steps to reliably reproduce this issue:

Open the browser console, click button to unmount player
https://stackblitz.com/edit/bitmovin-player-react-bug-report?file=src%2FApp.tsx

2024-11-13 20:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/bitmovin/bitmovin-player-react?pullRequest=18) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/bitmovin/bitmovin-player-react?pullRequest=18) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/bitmovin/bitmovin-player-react?pullRequest=18) it.</sub>

2024-11-14 19:09 UTC, ReallyBadNews commented
@karpov-kir whenever you have some time for a review I'd appreciate it

2024-11-21 14:01 UTC, karpov-kir requested changes
@ReallyBadNews, thank you for the contribution! The fix makes sense. Sorry for the long reply, I somehow overlooked the notification from GitHub.

I have left a few remarks. Please let me know if you can/want to follow up otherwise I can do it. 🙂

2024-11-21 19:35 UTC, ReallyBadNews commented
@karpov-kir no worries, my gh notifications are a black hole as well 😆 

Thanks for the notes, I've made the requested changes

2024-11-21 20:04 UTC, karpov-kir commented on src/BitmovinPlayer.tsx
> +    uiManager = undefined;
@ReallyBadNews, this line (215) is unnecessary and should be removed.

I think this is the last remark. 🙂

2024-11-22 08:26 UTC, felix-hoc reviewed
Looks good from my side as well once the final remark is addressed. Thanks for your contribution! :)

2024-11-22 17:27 UTC, ReallyBadNews commented
@karpov-kir @felix-hoc fixed that last note, appreciate the quick review!

2024-11-22 17:45 UTC, karpov-kir approved these changes

2024-11-22 17:46 UTC, merged

2024-11-22 18:02 UTC, karpov-kir commented
@ReallyBadNews, version 1.0.2 has been released. 👍🏻